### ISSUE TITLE
Do some sort of key verification

### ISSUE THREAD

**Issue by agallant** [agallant/dorabella#4]
Go for usability/security balance, e.g. calculate some literate sentence based on public key.

**Comment by soycode** [comment]
Another possibility: http://en.wikipedia.org/wiki/Socialist_millionaire

**Comment by soycode** [comment]
Minimalist solution I'm going to take for now - display key fingerprint (instead of the full public key - though maybe still expose that optionally) and let users manually verify that out-of-band (maybe give them a field to paste their friends into that checks it so they don't have to literally compare characters).
